name: Backend CI/CD

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
        working-directory: backend

      - name: Run Linter & Tests
        run: |
          npm run lint
          npm test
        working-directory: backend

      - name: Deploy to AWS (EC2 or Lambda)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying Backend..."
          # Add deployment script (AWS, Heroku, etc.)
